config/routes.rb
Rails.application.routes.draw do

  get 'members/index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :tickets
  resources :members
 
  root 'members#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_and_belongs_to_many :tickets
  has_many :tasks 
end

app/models/member.rb
class Member < ApplicationRecord
	has_many :tickets, dependent: :destroy


  # attr_accessible :first_name, :last_name, :email, :password
  has_secure_password


  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }


end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :issues	
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :member, required: false
  has_and_belongs_to_many :issues

  def self.search(search)
  where("number LIKE ? OR status LIKE ?", "%#{search}%", "%#{search}%") 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception
	include SessionsHelper
	
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :logged_in_member, only: [:index, :edit, :update, :destroy]
  before_action :correct_member,   only: [:edit, :update]    
  before_action :admin_member,     only: :destroy

  def show
    @member = Member.find(params[:id])
  end	

 def new
    @member = Member.new
 end

 def index
 	@members = Member.all
 end



 def create
   @member = Member.new(member_params)

   if @member.save
      log_in @member
      flash[:success] = "Boom - Welcome to the Support Org Checklist App!"
      redirect_to @member
   else
      flash[:danger] = "Try Again!"
      render 'new'
    end
 end

  def edit
    @member = Member.find(params[:id])
  end 

  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(member_params)
      flash[:success] = "Profile updated"
      redirect_to @member
    else
      render 'edit'
    end  
  end

  def destroy
    Member.find(params[:id]).destroy
    flash[:success] = "Member deleted"
    redirect_to members_url
  end  
 
 private
   def member_params
     params.require(:member).permit(:name, :email, :password, :password_confirmation)
   end

    def logged_in_member
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end   

    def correct_member
      @member = Member.find(params[:id])
      redirect_to(root_url) unless @member == current_member
    end

    def admin_member
      redirect_to(root_url) unless current_member.admin?
    end    



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    member = Member.find_by(email: params[:session][:email].downcase)
    if member && member.authenticate(params[:session][:password])
      log_in member
      redirect_to member
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end  

  # def show
  # 	login_path
  # end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def show
    @ticket = Ticket.find(params[:id])
  end	

 def new
 end
 
def index
  @tickets = Ticket.all
  if params[:search]
    @tickets = Ticket.all.search(params[:search]).order("created_at DESC")
  else
    @tickets = Ticket.all.order("created_at DESC")
  end
end

 def create
   @ticket = Ticket.new(ticket_params)
 
   @ticket.save
   redirect_to @ticket
 end

 
 private
   def ticket_params
     params.require(:ticket).permit(:number, :status, :url)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given member.
  def log_in(member)
    session[:member_id] = member.id
  end

  def current_member?(member)
    member == current_member
  end  

  def current_member
    @current_member ||= Member.find_by(id: session[:member_id])
  end

  def logged_in?
    !current_member.nil?
  end

  def log_out
    session.delete(:member_id)
    @current_member = nil
  end  


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Support Org Checklist App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Members", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_member %></li>
              <li><%= link_to "Member Settings", edit_member_path(current_member) %></li>              
              <li><%= link_to "Add Whatever", '#' %></li>

              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Ticketflow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class = "container">
        <% flash.each do |key, value| %>
          <div class = "alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
  </body>
</html>

app/views/members/_members.html.erb
<li>

  <%= link_to member.name, member %>
  <% if current_member.admin? && !current_member?(member) %>
    | <%= link_to "delete", member, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/members/edit.html.erb
<% provide(:title, "Edit member") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <% if @member.errors.full_messages != nil %>
      <% @member.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
          <%end%>
        <%end%>
        
    <%= form_for(@member) do |f| %>


      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


    </div>
  </div>
</div>

app/views/members/index.html.erb
<h1>WELCOME</h1>
<p>Support Org Ticket Workflow</p>

<br>

<strong> Select a Member:
<% @members.each do |member| %>
<li>
  <%= link_to member.name, member %>
  <% if current_member.admin? && !current_member?(member) %>
    | <%= link_to "delete", member, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

<% end %>

<% if !logged_in? %>
 <h5><%= link_to "Not here? Click here to create", new_member_path %></h5>
<% end %>

<br>
<br>
 <strong>Find a Ticket!
<%= form_tag(tickets_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Tickets" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/members/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @member.errors.full_messages != nil %>
      <% @member.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
          <%end%>
        <%end%>


    <%= form_for(@member) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create Member", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/members/show.html.erb
<p>
  <strong>Team Member:</strong>
  <%= @member.name %>
</p>
 

<p>
  <strong>Email:</strong>
  <%= @member.name.downcase.gsub(' ', '.') %>@braze.com
</p>

<p>///these are notes: create new ticket
link_to {member.id} yea
</p>



<br>

<br>All Tickets:
<h4> <% @member.tickets.each do |ticket| %> </h4>
<br> <%= link_to "000#{ticket.id}", ticket%>  
<% end %>

app/views/tickets/index.html.erb
<% if @tickets.blank? %>
  <h4>There are no tickets containing the term <%= params[:search] %>.</h4>
<%else %>
<h4> We found (<%=@tickets.count%>) tickets that matched the criteria: "<%=params[:search]%>"</h4>


<h4> <% @tickets.each do |ticket| %> </h4>
<br> <%= link_to "000#{ticket.number}", ticket%> - <%= ticket.member.name %> 
	<% end %>
<% end %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>


<%= form_with scope: :ticket, url: tickets_path, local: true do |form| %>
  <p>
    <%= form.label :number %><br>
    <%= form.number_field :number %>
  </p>
 
  <p>
    <%= form.label :status %><br>
    <%= form.text_area :status %>
  </p>

    <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>



<strong>Choose all that Apply:</strong>
<br>(probably automatic:)
<br>General Troubleshooting
<br>Advance Troubleshooting

<br>Email 
<br>REST API
<br>Push
<br>IAM
<br>UX/UI
<br>Partner Integration
<br>Deeplinks & Universal Linking
<br>Currents



Choosing and submitting will redirect them to Ticket.Issues#index

<form action="/tickets" method="post">
  <label>Number:</label><br>
  <input type="text" name="ticket[number]"><br><br>
  <label>Status:</label><br>
  <textarea name="ticket[status]"></textarea><br>
  <label>Add Tags:</label><br>
  <input type="text" name="tags"><br>
  <input type="submit" value="Create Post"><br>
</form>

app/views/tickets/show.html.erb
<p>
  <strong>Ticket Number:</strong>
  000<%= @ticket.number %>
</p>
 
<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>URL:</strong>
  <%= @ticket.url %>
</p>

<!-- click on the issues  -->
<!-- hyperlink each issue (or check wcl for how i integrated checkboxes to select) -->

<!-- list all issues manually, then if issue(clicked on) create an issue based on that issue selected. Ex) if "Push" is selected @ticket.issues.create(category: "Push") -->

<!-- <p>
  <strong>Issues:</strong>
  <% @ticket.issues.each do |issue| %>
  <br><%= issue.category%>
  <% end %>
</p>
 -->

<!--  <p>
  <strong>Issues:</strong>
  <% Issue.all.each do |issue| %>
  <br><%= issue.category%>
  <% end %>
</p> -->